### ISSUE TITLE
请问 clint.ts 中类型为什么要使用 *__Output？

### ISSUE THREAD

**Issue by initialencounter** [KarinJS/kritor-ts#1]
例如这个 [EventStructure__Output](https://github.com/KarinJS/kritor-ts/blob/main/src/client.ts#L26)
![image](https://github.com/KarinJS/kritor-ts/assets/109729945/c8d907eb-0417-4380-a4f4-8365b872bd7f)
，它的类型是enum EventType 的 key
![image](https://github.com/KarinJS/kritor-ts/assets/109729945/b2f45fc3-dc45-4531-830b-f784150413fd)
，服务端不应该返回 enum EventType 的 key
![image](https://github.com/KarinJS/kritor-ts/assets/109729945/764dfbe8-c256-47e4-acf2-d24dc73bc438)
，而应该返回 enum EventType 的 value

**Comment by Simplxss** [comment]
没太明白你的意思 onCore是回调函数 grpc的回调函数参数类型都是*__Output

另外这里的定义应该等效于
type _kritor_event_EventType__Output = "EVENT_TYPE_CORE_EVENT" | "EVENT_TYPE_MESSAGE" | "EVENT_TYPE_NOTICE" | "EVENT_TYPE_REQUEST"

**Comment by initialencounter** [comment]
> 没太明白你的意思 onCore是回调函数 grpc的回调函数参数类型都是*__Output
> 
> 另外这里的定义应该等效于 type _kritor_event_EventType__Output = "EVENT_TYPE_CORE_EVENT" | "EVENT_TYPE_MESSAGE" | "EVENT_TYPE_NOTICE" | "EVENT_TYPE_REQUEST"

这个回调函数传入的参数应该被算作客户端接收服务器的数据，或者说是服务端响应客户端的数据

我想可能是 `*__Output` 这个类型生成的时候把 key 、value 弄反了，我觉得这个类型 `_kritor_event_EventType__Output` 的期待值应该是 `0 | 1 | 2 | 3`, 因为服务端不应该返回 enum EventType的key `"EVENT_TYPE_CORE_EVENT"`

我们在生成类型的命令上做了一些修改，[fix: type definition](https://github.com/idanran/koishi-plugin-adapter-kritor/commit/092146849fe69417239076e37e610e3480cc7bdc)，把这个`_kritor_event_EventType__Output`的类型改成了枚举的value，麻烦您看一下这么做是否是正确的？

**Comment by Simplxss** [comment]
好的 我测试了一下确实原来生成的有问题 谢谢提醒
